version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  personal_info_service:
    build: ./personal_info_service
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
    ports:
      - "8001:8001"

  experience_service:
    build: ./experience_service
    command: uvicorn main:app --host 0.0.0.0 --port 8002
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
    ports:
      - "8002:8002"

volumes:
  mongo-data: